# Generated by Django 2.1.5 on 2019-12-30 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='companies',
            new_name='Stock',
        ),
    ]
